# This workflow will build a Java project with Ant
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-java-with-ant

name: Java CI

on:
  # push:
  #   branches: [ "main" ]
  # pull_request:
  #   branches: [ "main" ]
  workflow_dispatch:
    inputs:
      environment:
        description: "Выберите окружение"
        required: true
        default: "staging"
        type: choice
        options:
          - staging
          - production
    branches: [ "main" ]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up JDK 22
        uses: actions/setup-java@v3
        with:
          java-version: '22'
          distribution: 'temurin'

      - name: SSH and deploy
        uses: appleboy/ssh-action@v1
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USERNAME }}
          key: ${{ secrets.SSH_KEY }}
          script: |
            # Stop service
            sudo systemctl stop l2j_runner.service || true

            # Удаляем папку build
            if [ -d "build" ]; then
              rm -R build
            fi
            

            # идем в server и обновляем проект
            if [ -d "server" ]; then
              cd server
              git pull origin main
            else
              git clone -b main git@github.com:Soulofclassic/server.git server
              cd server
            fi

            # билдим проект
            ant

            # распаковываем получившийся пакет
            cd ..
            cd build
            unzip L2J_Mobius_Classic_3.0_TheKamael.zip

            # меняем права на все
            cd ..
            chmod -R 777 build/

            # стартуем сервис
            sudo systemctl start l2j_runner.service || true
            # Update or clone repository
            #if [ -d "/path/to/server" ]; then
            #  cd /path/to/server
            #  git pull origin main
            #else
            #  git clone -b main git@github.com:Soulofclassic/server.git /path/to/server
            #  cd /path/to/server
            #fi
           # 
            # Build project
            #ant
            
            # Set permissions
            #sudo chmod -R 777 ./build
            
            # Start service
            #sudo systemctl start l2j_runner.service
